/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated.guide'
import { Route as AuthenticatedFoundersRouteImport } from './routes/_authenticated/founders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedOsIndexRouteImport } from './routes/_authenticated/os.index'
import { Route as AuthenticatedOsTranscriptsRouteImport } from './routes/_authenticated/os.transcripts'
import { Route as AuthenticatedOsSimulationsRouteImport } from './routes/_authenticated/os.simulations'
import { Route as AuthenticatedOsReviewRouteImport } from './routes/_authenticated/os.review'
import { Route as AuthenticatedOsQuestionnaireRouteImport } from './routes/_authenticated/os.questionnaire'
import { Route as AuthenticatedOsOnboardingRouteImport } from './routes/_authenticated/os.onboarding'
import { Route as AuthenticatedOsMentorsRouteImport } from './routes/_authenticated/os.mentors'
import { Route as AuthenticatedOsMentorReviewRouteImport } from './routes/_authenticated/os.mentor-review'
import { Route as AuthenticatedOsLeadershipRouteImport } from './routes/_authenticated/os.leadership'
import { Route as AuthenticatedOsEventsRouteImport } from './routes/_authenticated/os.events'
import { Route as AuthenticatedOsDossiersRouteImport } from './routes/_authenticated/os.dossiers'
import { Route as AuthenticatedOsCommitteesRouteImport } from './routes/_authenticated/os.committees'
import { Route as AuthenticatedOsBiweeklyRouteImport } from './routes/_authenticated/os.biweekly'
import { Route as AuthenticatedOsAgentsRouteImport } from './routes/_authenticated/os.agents'
import { Route as AuthenticatedFoundersIdRouteImport } from './routes/_authenticated/founders.$id'
import { Route as AuthenticatedAdminBaselineRouteImport } from './routes/_authenticated/admin.baseline'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksAgentsTickRouteImport } from './routes/api/public/hooks/agents-tick'
import { Route as AuthenticatedOsWorkspaceFounderIdRouteImport } from './routes/_authenticated/os.workspace.$founderId'
import { Route as AuthenticatedOsReviewPacketIdRouteImport } from './routes/_authenticated/os.review.$packetId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFoundersRoute = AuthenticatedFoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOsIndexRoute = AuthenticatedOsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsTranscriptsRoute =
  AuthenticatedOsTranscriptsRouteImport.update({
    id: '/transcripts',
    path: '/transcripts',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsSimulationsRoute =
  AuthenticatedOsSimulationsRouteImport.update({
    id: '/simulations',
    path: '/simulations',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsReviewRoute = AuthenticatedOsReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsQuestionnaireRoute =
  AuthenticatedOsQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsOnboardingRoute =
  AuthenticatedOsOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsMentorsRoute = AuthenticatedOsMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsMentorReviewRoute =
  AuthenticatedOsMentorReviewRouteImport.update({
    id: '/mentor-review',
    path: '/mentor-review',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsLeadershipRoute =
  AuthenticatedOsLeadershipRouteImport.update({
    id: '/leadership',
    path: '/leadership',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsEventsRoute = AuthenticatedOsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsDossiersRoute = AuthenticatedOsDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsCommitteesRoute =
  AuthenticatedOsCommitteesRouteImport.update({
    id: '/committees',
    path: '/committees',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsBiweeklyRoute = AuthenticatedOsBiweeklyRouteImport.update({
  id: '/biweekly',
  path: '/biweekly',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsAgentsRoute = AuthenticatedOsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedFoundersIdRoute = AuthenticatedFoundersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFoundersRoute,
} as any)
const AuthenticatedAdminBaselineRoute =
  AuthenticatedAdminBaselineRouteImport.update({
    id: '/baseline',
    path: '/baseline',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAgentsTickRoute =
  ApiPublicHooksAgentsTickRouteImport.update({
    id: '/api/public/hooks/agents-tick',
    path: '/api/public/hooks/agents-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOsWorkspaceFounderIdRoute =
  AuthenticatedOsWorkspaceFounderIdRouteImport.update({
    id: '/workspace/$founderId',
    path: '/workspace/$founderId',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsReviewPacketIdRoute =
  AuthenticatedOsReviewPacketIdRouteImport.update({
    id: '/$packetId',
    path: '/$packetId',
    getParentRoute: () => AuthenticatedOsReviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/founders': typeof AuthenticatedFoundersRouteWithChildren
  '/guide': typeof AuthenticatedGuideRoute
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/baseline': typeof AuthenticatedAdminBaselineRoute
  '/founders/$id': typeof AuthenticatedFoundersIdRoute
  '/os/agents': typeof AuthenticatedOsAgentsRoute
  '/os/biweekly': typeof AuthenticatedOsBiweeklyRoute
  '/os/committees': typeof AuthenticatedOsCommitteesRoute
  '/os/dossiers': typeof AuthenticatedOsDossiersRoute
  '/os/events': typeof AuthenticatedOsEventsRoute
  '/os/leadership': typeof AuthenticatedOsLeadershipRoute
  '/os/mentor-review': typeof AuthenticatedOsMentorReviewRoute
  '/os/mentors': typeof AuthenticatedOsMentorsRoute
  '/os/onboarding': typeof AuthenticatedOsOnboardingRoute
  '/os/questionnaire': typeof AuthenticatedOsQuestionnaireRoute
  '/os/review': typeof AuthenticatedOsReviewRouteWithChildren
  '/os/simulations': typeof AuthenticatedOsSimulationsRoute
  '/os/transcripts': typeof AuthenticatedOsTranscriptsRoute
  '/os/': typeof AuthenticatedOsIndexRoute
  '/os/review/$packetId': typeof AuthenticatedOsReviewPacketIdRoute
  '/os/workspace/$founderId': typeof AuthenticatedOsWorkspaceFounderIdRoute
  '/api/public/hooks/agents-tick': typeof ApiPublicHooksAgentsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/founders': typeof AuthenticatedFoundersRouteWithChildren
  '/guide': typeof AuthenticatedGuideRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/baseline': typeof AuthenticatedAdminBaselineRoute
  '/founders/$id': typeof AuthenticatedFoundersIdRoute
  '/os/agents': typeof AuthenticatedOsAgentsRoute
  '/os/biweekly': typeof AuthenticatedOsBiweeklyRoute
  '/os/committees': typeof AuthenticatedOsCommitteesRoute
  '/os/dossiers': typeof AuthenticatedOsDossiersRoute
  '/os/events': typeof AuthenticatedOsEventsRoute
  '/os/leadership': typeof AuthenticatedOsLeadershipRoute
  '/os/mentor-review': typeof AuthenticatedOsMentorReviewRoute
  '/os/mentors': typeof AuthenticatedOsMentorsRoute
  '/os/onboarding': typeof AuthenticatedOsOnboardingRoute
  '/os/questionnaire': typeof AuthenticatedOsQuestionnaireRoute
  '/os/review': typeof AuthenticatedOsReviewRouteWithChildren
  '/os/simulations': typeof AuthenticatedOsSimulationsRoute
  '/os/transcripts': typeof AuthenticatedOsTranscriptsRoute
  '/os': typeof AuthenticatedOsIndexRoute
  '/os/review/$packetId': typeof AuthenticatedOsReviewPacketIdRoute
  '/os/workspace/$founderId': typeof AuthenticatedOsWorkspaceFounderIdRoute
  '/api/public/hooks/agents-tick': typeof ApiPublicHooksAgentsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/founders': typeof AuthenticatedFoundersRouteWithChildren
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/os': typeof AuthenticatedOsRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/baseline': typeof AuthenticatedAdminBaselineRoute
  '/_authenticated/founders/$id': typeof AuthenticatedFoundersIdRoute
  '/_authenticated/os/agents': typeof AuthenticatedOsAgentsRoute
  '/_authenticated/os/biweekly': typeof AuthenticatedOsBiweeklyRoute
  '/_authenticated/os/committees': typeof AuthenticatedOsCommitteesRoute
  '/_authenticated/os/dossiers': typeof AuthenticatedOsDossiersRoute
  '/_authenticated/os/events': typeof AuthenticatedOsEventsRoute
  '/_authenticated/os/leadership': typeof AuthenticatedOsLeadershipRoute
  '/_authenticated/os/mentor-review': typeof AuthenticatedOsMentorReviewRoute
  '/_authenticated/os/mentors': typeof AuthenticatedOsMentorsRoute
  '/_authenticated/os/onboarding': typeof AuthenticatedOsOnboardingRoute
  '/_authenticated/os/questionnaire': typeof AuthenticatedOsQuestionnaireRoute
  '/_authenticated/os/review': typeof AuthenticatedOsReviewRouteWithChildren
  '/_authenticated/os/simulations': typeof AuthenticatedOsSimulationsRoute
  '/_authenticated/os/transcripts': typeof AuthenticatedOsTranscriptsRoute
  '/_authenticated/os/': typeof AuthenticatedOsIndexRoute
  '/_authenticated/os/review/$packetId': typeof AuthenticatedOsReviewPacketIdRoute
  '/_authenticated/os/workspace/$founderId': typeof AuthenticatedOsWorkspaceFounderIdRoute
  '/api/public/hooks/agents-tick': typeof ApiPublicHooksAgentsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/founders'
    | '/guide'
    | '/os'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/baseline'
    | '/founders/$id'
    | '/os/agents'
    | '/os/biweekly'
    | '/os/committees'
    | '/os/dossiers'
    | '/os/events'
    | '/os/leadership'
    | '/os/mentor-review'
    | '/os/mentors'
    | '/os/onboarding'
    | '/os/questionnaire'
    | '/os/review'
    | '/os/simulations'
    | '/os/transcripts'
    | '/os/'
    | '/os/review/$packetId'
    | '/os/workspace/$founderId'
    | '/api/public/hooks/agents-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/founders'
    | '/guide'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/baseline'
    | '/founders/$id'
    | '/os/agents'
    | '/os/biweekly'
    | '/os/committees'
    | '/os/dossiers'
    | '/os/events'
    | '/os/leadership'
    | '/os/mentor-review'
    | '/os/mentors'
    | '/os/onboarding'
    | '/os/questionnaire'
    | '/os/review'
    | '/os/simulations'
    | '/os/transcripts'
    | '/os'
    | '/os/review/$packetId'
    | '/os/workspace/$founderId'
    | '/api/public/hooks/agents-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/founders'
    | '/_authenticated/guide'
    | '/_authenticated/os'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/baseline'
    | '/_authenticated/founders/$id'
    | '/_authenticated/os/agents'
    | '/_authenticated/os/biweekly'
    | '/_authenticated/os/committees'
    | '/_authenticated/os/dossiers'
    | '/_authenticated/os/events'
    | '/_authenticated/os/leadership'
    | '/_authenticated/os/mentor-review'
    | '/_authenticated/os/mentors'
    | '/_authenticated/os/onboarding'
    | '/_authenticated/os/questionnaire'
    | '/_authenticated/os/review'
    | '/_authenticated/os/simulations'
    | '/_authenticated/os/transcripts'
    | '/_authenticated/os/'
    | '/_authenticated/os/review/$packetId'
    | '/_authenticated/os/workspace/$founderId'
    | '/api/public/hooks/agents-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksAgentsTickRoute: typeof ApiPublicHooksAgentsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/founders': {
      id: '/_authenticated/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof AuthenticatedFoundersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/os/': {
      id: '/_authenticated/os/'
      path: '/'
      fullPath: '/os/'
      preLoaderRoute: typeof AuthenticatedOsIndexRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/transcripts': {
      id: '/_authenticated/os/transcripts'
      path: '/transcripts'
      fullPath: '/os/transcripts'
      preLoaderRoute: typeof AuthenticatedOsTranscriptsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/simulations': {
      id: '/_authenticated/os/simulations'
      path: '/simulations'
      fullPath: '/os/simulations'
      preLoaderRoute: typeof AuthenticatedOsSimulationsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/review': {
      id: '/_authenticated/os/review'
      path: '/review'
      fullPath: '/os/review'
      preLoaderRoute: typeof AuthenticatedOsReviewRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/questionnaire': {
      id: '/_authenticated/os/questionnaire'
      path: '/questionnaire'
      fullPath: '/os/questionnaire'
      preLoaderRoute: typeof AuthenticatedOsQuestionnaireRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/onboarding': {
      id: '/_authenticated/os/onboarding'
      path: '/onboarding'
      fullPath: '/os/onboarding'
      preLoaderRoute: typeof AuthenticatedOsOnboardingRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/mentors': {
      id: '/_authenticated/os/mentors'
      path: '/mentors'
      fullPath: '/os/mentors'
      preLoaderRoute: typeof AuthenticatedOsMentorsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/mentor-review': {
      id: '/_authenticated/os/mentor-review'
      path: '/mentor-review'
      fullPath: '/os/mentor-review'
      preLoaderRoute: typeof AuthenticatedOsMentorReviewRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/leadership': {
      id: '/_authenticated/os/leadership'
      path: '/leadership'
      fullPath: '/os/leadership'
      preLoaderRoute: typeof AuthenticatedOsLeadershipRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/events': {
      id: '/_authenticated/os/events'
      path: '/events'
      fullPath: '/os/events'
      preLoaderRoute: typeof AuthenticatedOsEventsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/dossiers': {
      id: '/_authenticated/os/dossiers'
      path: '/dossiers'
      fullPath: '/os/dossiers'
      preLoaderRoute: typeof AuthenticatedOsDossiersRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/committees': {
      id: '/_authenticated/os/committees'
      path: '/committees'
      fullPath: '/os/committees'
      preLoaderRoute: typeof AuthenticatedOsCommitteesRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/biweekly': {
      id: '/_authenticated/os/biweekly'
      path: '/biweekly'
      fullPath: '/os/biweekly'
      preLoaderRoute: typeof AuthenticatedOsBiweeklyRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/agents': {
      id: '/_authenticated/os/agents'
      path: '/agents'
      fullPath: '/os/agents'
      preLoaderRoute: typeof AuthenticatedOsAgentsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/founders/$id': {
      id: '/_authenticated/founders/$id'
      path: '/$id'
      fullPath: '/founders/$id'
      preLoaderRoute: typeof AuthenticatedFoundersIdRouteImport
      parentRoute: typeof AuthenticatedFoundersRoute
    }
    '/_authenticated/admin/baseline': {
      id: '/_authenticated/admin/baseline'
      path: '/baseline'
      fullPath: '/admin/baseline'
      preLoaderRoute: typeof AuthenticatedAdminBaselineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents-tick': {
      id: '/api/public/hooks/agents-tick'
      path: '/api/public/hooks/agents-tick'
      fullPath: '/api/public/hooks/agents-tick'
      preLoaderRoute: typeof ApiPublicHooksAgentsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/os/workspace/$founderId': {
      id: '/_authenticated/os/workspace/$founderId'
      path: '/workspace/$founderId'
      fullPath: '/os/workspace/$founderId'
      preLoaderRoute: typeof AuthenticatedOsWorkspaceFounderIdRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/review/$packetId': {
      id: '/_authenticated/os/review/$packetId'
      path: '/$packetId'
      fullPath: '/os/review/$packetId'
      preLoaderRoute: typeof AuthenticatedOsReviewPacketIdRouteImport
      parentRoute: typeof AuthenticatedOsReviewRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBaselineRoute: typeof AuthenticatedAdminBaselineRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBaselineRoute: AuthenticatedAdminBaselineRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedFoundersRouteChildren {
  AuthenticatedFoundersIdRoute: typeof AuthenticatedFoundersIdRoute
}

const AuthenticatedFoundersRouteChildren: AuthenticatedFoundersRouteChildren = {
  AuthenticatedFoundersIdRoute: AuthenticatedFoundersIdRoute,
}

const AuthenticatedFoundersRouteWithChildren =
  AuthenticatedFoundersRoute._addFileChildren(
    AuthenticatedFoundersRouteChildren,
  )

interface AuthenticatedOsReviewRouteChildren {
  AuthenticatedOsReviewPacketIdRoute: typeof AuthenticatedOsReviewPacketIdRoute
}

const AuthenticatedOsReviewRouteChildren: AuthenticatedOsReviewRouteChildren = {
  AuthenticatedOsReviewPacketIdRoute: AuthenticatedOsReviewPacketIdRoute,
}

const AuthenticatedOsReviewRouteWithChildren =
  AuthenticatedOsReviewRoute._addFileChildren(
    AuthenticatedOsReviewRouteChildren,
  )

interface AuthenticatedOsRouteChildren {
  AuthenticatedOsAgentsRoute: typeof AuthenticatedOsAgentsRoute
  AuthenticatedOsBiweeklyRoute: typeof AuthenticatedOsBiweeklyRoute
  AuthenticatedOsCommitteesRoute: typeof AuthenticatedOsCommitteesRoute
  AuthenticatedOsDossiersRoute: typeof AuthenticatedOsDossiersRoute
  AuthenticatedOsEventsRoute: typeof AuthenticatedOsEventsRoute
  AuthenticatedOsLeadershipRoute: typeof AuthenticatedOsLeadershipRoute
  AuthenticatedOsMentorReviewRoute: typeof AuthenticatedOsMentorReviewRoute
  AuthenticatedOsMentorsRoute: typeof AuthenticatedOsMentorsRoute
  AuthenticatedOsOnboardingRoute: typeof AuthenticatedOsOnboardingRoute
  AuthenticatedOsQuestionnaireRoute: typeof AuthenticatedOsQuestionnaireRoute
  AuthenticatedOsReviewRoute: typeof AuthenticatedOsReviewRouteWithChildren
  AuthenticatedOsSimulationsRoute: typeof AuthenticatedOsSimulationsRoute
  AuthenticatedOsTranscriptsRoute: typeof AuthenticatedOsTranscriptsRoute
  AuthenticatedOsIndexRoute: typeof AuthenticatedOsIndexRoute
  AuthenticatedOsWorkspaceFounderIdRoute: typeof AuthenticatedOsWorkspaceFounderIdRoute
}

const AuthenticatedOsRouteChildren: AuthenticatedOsRouteChildren = {
  AuthenticatedOsAgentsRoute: AuthenticatedOsAgentsRoute,
  AuthenticatedOsBiweeklyRoute: AuthenticatedOsBiweeklyRoute,
  AuthenticatedOsCommitteesRoute: AuthenticatedOsCommitteesRoute,
  AuthenticatedOsDossiersRoute: AuthenticatedOsDossiersRoute,
  AuthenticatedOsEventsRoute: AuthenticatedOsEventsRoute,
  AuthenticatedOsLeadershipRoute: AuthenticatedOsLeadershipRoute,
  AuthenticatedOsMentorReviewRoute: AuthenticatedOsMentorReviewRoute,
  AuthenticatedOsMentorsRoute: AuthenticatedOsMentorsRoute,
  AuthenticatedOsOnboardingRoute: AuthenticatedOsOnboardingRoute,
  AuthenticatedOsQuestionnaireRoute: AuthenticatedOsQuestionnaireRoute,
  AuthenticatedOsReviewRoute: AuthenticatedOsReviewRouteWithChildren,
  AuthenticatedOsSimulationsRoute: AuthenticatedOsSimulationsRoute,
  AuthenticatedOsTranscriptsRoute: AuthenticatedOsTranscriptsRoute,
  AuthenticatedOsIndexRoute: AuthenticatedOsIndexRoute,
  AuthenticatedOsWorkspaceFounderIdRoute:
    AuthenticatedOsWorkspaceFounderIdRoute,
}

const AuthenticatedOsRouteWithChildren = AuthenticatedOsRoute._addFileChildren(
  AuthenticatedOsRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFoundersRoute: typeof AuthenticatedFoundersRouteWithChildren
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedOsRoute: typeof AuthenticatedOsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFoundersRoute: AuthenticatedFoundersRouteWithChildren,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedOsRoute: AuthenticatedOsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksAgentsTickRoute: ApiPublicHooksAgentsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
